### ISSUE TITLE
希望可以支持x86 64的库文件

### ISSUE THREAD

**Issue by yangzxstar** [easefun/polyv-android-sdk-demo#10]
现在很多平板都是x86 64的架构，希望可以支持

**Comment by tanqu2013** [comment]
预计这周发布一个27版本，将增加对x86_64的支持

**Comment by tanqu2013** [comment]
发布了新版，支持x86_64
https://github.com/easefun/polyv-android-sdk-demo/releases/tag/v1.0.27
