### ISSUE TITLE
【咨询】库中的ijkplayer可以直接使用播放其他视频吗

### ISSUE THREAD

**Issue by xiang-xx** [easefun/polyv-android-sdk-demo#11]
项目需求是
1.既要使用保利sdk播放部分视频，
2.又要播放其他视频，比如七牛云上存的视频。

我播放七牛云视频打算使用**ijkplayer**，后来发现保利**sdk**集成了**ijkplayer**，所以想了解一下能否直接使用sdk中的ijkplayer播放其他视频。

**Comment by tanqu2013** [comment]
IjkVideoView.setVideoPath 可以播放网络地址的mp4,flv,hls 视频
