### ISSUE TITLE
什么时候可以改成gradle的方式

### ISSUE THREAD

**Issue by yangzxstar** [easefun/polyv-android-sdk-demo#2]

**Comment by tanqu2013** [comment]
暂时还不会支持，如果准备支持gradle再告知

**Comment by tanqu2013** [comment]
https://github.com/easefun/polyv-android-sdk-demo/wiki/9.%E4%BB%8E-ADT%EF%BC%88Eclipse%EF%BC%89-%E8%BD%AC%E5%88%B0-Android-Studio
这里有教如何转成Android-Studio项目。
