### ISSUE TITLE
Android客户端播放视频频繁loading，报如下log。但是已确认网络状况很好，并且在保利威视视频在Web端播放流畅。请问是什么原因导致该问题的？

### ISSUE THREAD

**Issue by LiYaHX** [easefun/polyv-android-sdk-demo#3]
11-13 22:26:37.867: I/System.out(10474): (HTTPLog)-Static: isSBSettingEnabled false
11-13 22:26:37.887: I/System.out(10474): KnoxVpnUidStorageknoxVpnSupported API value returned is false

**Comment by tanqu2013** [comment]
输出信息不能准确的看出和定位问题，如果需要解决，可以与我们的技术支持联系。或者输出更多log供我们定位问题。
