### ISSUE TITLE
程序混淆后点击播放视频，程序异常退出，log日志如下

### ISSUE THREAD

**Issue by LiYaHX** [easefun/polyv-android-sdk-demo#4]
12-17 20:25:03.199: E/IJKMEDIA(6472): missing mNativeMediaPlayer
12-17 20:25:03.209: E/AndroidRuntime(6472): FATAL EXCEPTION: main
12-17 20:25:03.209: E/AndroidRuntime(6472): java.lang.NoSuchFieldError: no field with name='mNativeMediaPlayer' signature='J' in class Ltv/danmaku/ijk/media/player/IjkMediaPlayer;
12-17 20:25:03.209: E/AndroidRuntime(6472):     at java.lang.Runtime.nativeLoad(Native Method)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at java.lang.Runtime.doLoad(Runtime.java:432)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at java.lang.Runtime.loadLibrary(Runtime.java:360)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at java.lang.System.loadLibrary(System.java:525)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at tv.danmaku.ijk.media.player.k.a(Unknown Source)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at tv.danmaku.ijk.media.player.IjkMediaPlayer.a(Unknown Source)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(Unknown Source)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at tv.danmaku.ijk.media.player.IjkMediaPlayer.<init>(Unknown Source)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at com.easefun.polyvsdk.ijk.IjkVideoView.j(Unknown Source)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at com.easefun.polyvsdk.ijk.IjkVideoView.setVideoURI(Unknown Source)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at com.easefun.polyvsdk.ijk.av.a(Unknown Source)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at com.easefun.polyvsdk.ijk.av.onPostExecute(Unknown Source)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at android.os.AsyncTask.finish(AsyncTask.java:631)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at android.os.AsyncTask.access$600(AsyncTask.java:177)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at android.os.Handler.dispatchMessage(Handler.java:99)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at android.os.Looper.loop(Looper.java:137)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at android.app.ActivityThread.main(ActivityThread.java:5450)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at java.lang.reflect.Method.invokeNative(Native Method)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at java.lang.reflect.Method.invoke(Method.java:525)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
12-17 20:25:03.209: E/AndroidRuntime(6472):     at dalvik.system.NativeStart.main(Native Method)
12-17 20:25:03.219: E/StatusBar.NetworkController(1056): refreshSignalCluster: roam
12-17 20:25:03.219: E/StatusBar.NetworkController(1056): refreshSignalCluster: set mShowPhoneRSSIForData = false

**Comment by easefun** [comment]
proguard文件是怎么配置的？

**Comment by LiYaHX** [comment]
-ignorewarnings                     # 忽略警告，避免打包时某些警告出现
-optimizationpasses 5               # 指定代码的压缩级别
-dontusemixedcaseclassnames         # 是否使用大小写混合
-dontskipnonpubliclibraryclasses    # 是否混淆第三方jar
-dontpreverify                      # 混淆时是否做预校验
-verbose                            # 混淆时是否记录日志
-optimizations !code/simplification/arithmetic,!field/*,!class/merging/*  # 混淆时所采用的算法s

-dontwarn android.support.v4.*\*  
-dontwarn android.os.**

-keep class android.support.v4.*\* { _; }        # 保持哪些类不被混淆
-keep class com.baidu._\* { _; }  
-keep class vi.com.gdi.bgl.android.__{_;}
-keep class android.os.*_{_;}

-keep interface android.support.v4.app.*\* { _; }  
-keep public class \* extends android.support.v4._\*  
-keep public class \* extends android.app.Fragment
-keep public class \* extends android.app.Activity
-keep public class \* extends android.app.Application
-keep public class \* extends android.app.Service
-keep public class \* extends android.content.BroadcastReceiver
-keep public class \* extends android.content.ContentProvider
-keep public class \* extends android.support.v4.widget
-keep public class \* extends com.sqlcrypt.database
-keep public class \* extends com.sqlcrypt.database.sqlite
-keep public class \* extends com.treecore.**
-keep public class \* extends de.greenrobot.dao.**

-keepclasseswithmembernames class \* {                       # 保持 native 方法不被混淆
    native <methods>;
}

-keepclasseswithmembers class \* {                           # 保持自定义控件类不被混淆
    public <init>(android.content.Context, android.util.AttributeSet);
}

-keepclasseswithmembers class \* {                           # 保持自定义控件类不被混淆
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

-keepclassmembers class \* extends android.app.Activity {    # 保持类成员
   public void *(android.view.View);
}

-keepclassmembers enum \* {                                  # 保持枚举 enum 类不被混淆
    public static *_[] values();
    public static *_ valueOf(java.lang.String);
}

-keep class \* implements android.os.Parcelable {            # 保持 Parcelable 不被混淆
  public static final android.os.Parcelable$Creator *;
}

################ IM ####################
-keep class com.easemob.*\* {_;}
-keep class org.jivesoftware._\* {_;}
-keep class org.apache._\* {_;}
-dontwarn  com.easemob._*
#2.0.9后的不需要加下面这个keep
#-keep class org.xbill.DNS.*\* {_;}
#另外，demo中发送表情的时候使用到反射，需要keep SmileUtils,注意前面的包名，
#不要SmileUtils复制到自己的项目下keep的时候还是写的demo里的包名
-keep class com.easemob.chatuidemo.utils.SmileUtils {_;}

#2.0.9后加入语音通话功能，如需使用此功能的api，加入以下keep
-dontwarn ch.imvs.**
-dontwarn org.slf4j.**
-keep class org.ice4j.*\* {_;}
-keep class net.java.sip._\* {_;}
-keep class org.webrtc.voiceengine._\* {_;}
-keep class org.bitlet._\* {_;}
-keep class org.slf4j._\* {_;}
-keep class ch.imvs._\* {*;}

######################## UMeng ########################
-keepclassmembers class \* {
   public <init>(org.json.JSONObject);
}

######################## polyv ########################
-keep class com.easefun.polyvsdk.**
-keep class tv.danmaku.ijk.media.**
-keep class com.nostra13.universalimageloader.**
-keep class org.apache.http.**
-keep class org.apache.commons.**

另：Eclipse混淆后能正常播放视频，而AndroidStudio混淆后则报上述异常。我用的是AndroidStudio混淆的。

**Comment by LiYaHX** [comment]
附注：上述StackTrace是在Samsung Galaxy Note3  Android4.3上出现的。

在Samsung Galaxy Note3  Android5.0的StackTrace如下：
12-18 11:36:38.645: E/art(4488): Failed to register native method tv.danmaku.ijk.media.player.IjkMediaPlayer._stop()V in /data/app/com.nbang.consumer-1/base.apk
12-18 11:36:38.655: A/art(4488): art/runtime/thread.cc:1116] Throwing new exception 'no "J" field "mNativeMediaPlayer" in class "Ltv/danmaku/ijk/media/player/IjkMediaPlayer;" or its superclasses' with unexpected pending exception: java.lang.NoSuchMethodError: no static or non-static method "Ltv/danmaku/ijk/media/player/IjkMediaPlayer;._stop()V"
12-18 11:36:38.655: A/art(4488): art/runtime/thread.cc:1116]   at java.lang.String java.lang.Runtime.nativeLoad(java.lang.String, java.lang.ClassLoader, java.lang.String) (Runtime.java:-2)
12-18 11:36:38.655: A/art(4488): art/runtime/thread.cc:1116]   at java.lang.String java.lang.Runtime.doLoad(java.lang.String, java.lang.ClassLoader) (Runtime.java:428)
12-18 11:36:38.655: A/art(4488): art/runtime/thread.cc:1116]   at void java.lang.Runtime.loadLibrary(java.lang.String, java.lang.ClassLoader) (Runtime.java:369)
12-18 11:36:38.655: A/art(4488): art/runtime/thread.cc:1116]   at void java.lang.System.loadLibrary(java.lang.String) (System.java:989)
12-18 11:36:38.655: A/art(4488): art/runtime/thread.cc:1116]   at void tv.danmaku.ijk.media.player.IjkMediaPlayer$1.a(java.lang.String)

**Comment by tanqu2013** [comment]
-keep @interface tv.danmaku.ijk.media.**

加上这个试试，报错的代码是mNativeMediaPlayer
源代码是:
IjkMediaPlayer 中的一段代码
@AccessedByNative

##   private long mNativeMediaPlayer;

package tv.danmaku.ijk.media.player.annotations;

import .....

@Target({java.lang.annotation.ElementType.FIELD})
@Retention(RetentionPolicy.CLASS)
public @interface AccessedByNative {}

**Comment by LiYaHX** [comment]
谢谢，已解决。

解决方案：（1）修改混淆配置文件； （2）修改widget获取方式 。具体如下所示：

（1）修改混淆配置文件：

#----------------------- polyv -----------------------#
-keep class com.easefun.polyvsdk.*\* { _; }
-keep class tv.danmaku.ijk.media._\* { _; }
-keep @interface tv.danmaku.ijk.media._\* { _; }
-keep class com.nostra13.universalimageloader._\* { _; }
-keep class org.apache.http._\* { _; }
-keep class org.apache.commons._\* { *; }

（2）修改widget获取方式

在MediaController类的initControllerView(View v)方法中，通过反射 无法正确获取到widget，在混淆配置文件中即使不混淆R文件也同样无法获取到。最终，通过R.id.mediacontroller_play_pause可正确获取到widget。
       可以问下为什么采用了 反射机制 去获取 widget 吗？

**Comment by tanqu2013** [comment]
这是我应该做的。
非常感谢你把结论发出来，并且告知解决方法，赞扬你这种伟大的行为，感谢。
为什么采用反射机制去获取widget，我了解清楚将再次更新消息。

**Comment by tanqu2013** [comment]
关于MediaController中为什么使用反射机制取得resourceId
因为以前有一个库项目和一个主项目，库项目中不能直接使用R.id.resourceId 取得资源id，所以使用了反射机制，后来库项目合并到主项目中，我已经修改好并且更新上来了，直接使用R.id.resourceId取得资源，谢谢你好心的提醒。

**Comment by LiYaHX** [comment]
OK，了解。非常感谢您的详细回复～。 

另：不客气。:)
