### ISSUE TITLE
播放和上传问题

### ISSUE THREAD

**Issue by super-hu** [easefun/polyv-android-sdk-demo#8]
1.播放按Home键到后台，再进去又从新播放了。
2.上传视频有错误的回调吗？
3.上传有暂停、继续的操作吗？

**Comment by tanqu2013** [comment]
问题1我们已记录，安排处理了
问题2,3我们已记录，安排处理了
我们处理好了，会再次更新消息

**Comment by tanqu2013** [comment]
问题2,3 对应的功能已经增加

**Comment by tanqu2013** [comment]
增加了home健到后台，再进去从上次播放点开始播放
https://github.com/easefun/polyv-android-sdk-demo/releases/tag/v1.0.27
