### ISSUE TITLE
切换码率重新播放

### ISSUE THREAD

**Issue by ghost** [easefun/polyv-android-sdk-demo#9]
运行你们的Demo发现，当我切换码率的时候就重新开始播放了。这个应该如何调整，求告知

**Comment by tanqu2013** [comment]
我们发布了新版，https://github.com/easefun/polyv-android-sdk-demo/releases/tag/v1.0.26 解决这个问题

**Comment by ghost** [comment]
更新了你们的新版本，但是这个问题没有完全解决，当我在一个时间点切换码率它可能会成功到这个点，当我继续播放，过一段时间再切换码率，它任然是回到第一个时间点。这个我自己写的回调在点击切换码率的时候记录了时间点，在切换成功后跳到这个点暂时解决了这个问题。希望你们下个版本可以把这个问题能够解决下。还有进度条的那个第二条加载，它会加载到快到终点的时候就停止了，这个我不太知道怎么去控制，希望可以告知下，谢谢！

**Comment by tanqu2013** [comment]
谢谢你告诉我们切换码率的这个问题，我们会安排修复。
第二条加载是缓存加载，播放器内部传过来的值不会到达最大值，所以进度条加载不满，这个我们想办法解决。

**Comment by tanqu2013** [comment]
码率问题已经修复
https://github.com/easefun/polyv-android-sdk-demo/releases/tag/v1.0.28

**Comment by ghost** [comment]
运行了下Demo，增加了很多厉害的功能，不过我主要是来反馈一些问题的。
1、我在MediaController 这个类里面控制进度条的隐藏和显示都没有效果（我技术还不够），希望你们可以告知下怎么控制。因为不止进度条，还有我在这个页面添加一些自己的东西，但是想动态控制隐藏和显示都不行
2、我们需要一个3分钟后显示登录的东西，但是我没有找到合适的方法来设置3分钟这个监听的地方。你们有没有什么方法是可以让我监听的
3、视频右滑快进有问题，右滑操作进度条会直接到到结束位置

**Comment by tanqu2013** [comment]
2、我们需要一个3分钟后显示登录的东西，但是我没有找到合适的方法来设置3分钟这个监听的地方。你们有没有什么方法是可以让我监听的

没有提供这个接口，你可以用Handler 的sendMessageDelayed 来实现。

**Comment by ghost** [comment]
考虑过这个，但是你们的SDK播放的时候会有一个加载过程，如果加载时间达到一分钟，那么这么实现，用户实际上只看了两分钟，所以这些计时类方法不是特别理想

**Comment by tanqu2013** [comment]
可以在IjkVideoView.setOnPreparedListener 的回调方法中，然后再用Handler 的sendMessageDelayed 来实现。
OnPreparedListener 是视频表示加载完成了，准备播放就会回调。

**Comment by tanqu2013** [comment]
问题3已经修复
https://github.com/easefun/polyv-android-sdk-demo/releases/tag/v1.0.29

**Comment by tanqu2013** [comment]
请使用最新的SD，界面全部升级了。
https://github.com/easefun/polyv-android-sdk-2.0-demo
